server:
  port: 8100
spring:
  datasource:
    username: farm_order
    password: 1234
    url: jdbc:mysql://aitmaker.cn:3306/farm_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: aitmaker.cn:8848
  application:
    name: farm-order
mybatis-plus:
  mapper-locations: classpath:/mapper/order/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置逻辑删除 1代表删除 0代表已删除
      logic-delete-value: 1
      logic-not-delete-value: 0